version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      - GITHUB_TOKEN: YOUR_GH_TOKEN
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    draft: false
    prerelease: false
    files:
      - path: dist/bmi-checker-app_Windows_i386.zip
      - path: dist/bmi-checker-app_Windows_arm64.zip
      - path: dist/bmi-checker-app_Darwin_arm64.tar.gz
      - path: dist/bmi-checker-app_Darwin_x86_64.tar.gz
      - path: dist/bmi-checker-app_Linux_i386.tar.gz
      - path: dist/bmi-checker-app_Linux_x86_64.tar.gz
      - path: dist/bmi-checker-app_Linux_arm64.tar.gz
      - path: dist/bmi-checker-app_Windows_x86_64.zip
    api_token: $GITHUB_TOKEN
