project_name: your_project_name

builds:
  - id: default
    main: ./cmd/your_main_file.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - docs/

brews:
  - name: your_project_name
    homepage: https://your_project_homepage.com
    description: "Your project description"
    github:
      owner: your_github_username
      repo: your_project_name
    install: |
      bin.install "{{ .ProjectName }}"

dockers:
  - image_templates:
      - "ghcr.io/your_github_username/your_project_name:latest"
    dockerfile: ./Dockerfile
